import turtle
length=int(input("길이를 입력하세요 :"))
t=turtle.Turtle()
t.shape("turtle")
t.color("pink")
t.width(20)
t.forward(length)
t.left(90)
t.color("blue")
t.forward(length)
t.right(90)
t.forward(length)
t.right(90)
t.color("lawngreen")
t.forward(length)
t.left(90)
t.forward(length)
